---
title: "Quantum Computing - Technologiemanagement"
author: "Pablo Stockhausen"
date: "4 6 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. Install & import packages

### Install

```{r}
install.packages("tibble")
install.packages("dplyr")
install.packages("tidyr")
install.packages("igraph")
install.packages("tidyverse")
```

### Import

```{r}
library("igraph")
library("tibble")
library("dplyr")
library("tidyr")
library("tidyverse")
```


# 1. Data collection

Data set is given and contains patents regarding quantum computing.

Import data:
```{r}
df_qc <- read.csv("Quantum computing.csv", sep=";")
```

# 2. Data cleaning and mapping

Check if data set is in correct format
```{r}
df_qc <- tibble(df_qc)
```

Clean Data
```{r}
df_qc <- df_qc %>% 
  mutate(Inventors=strsplit(Inventors, "\n")) %>% 
  unnest(Inventors)
```

### Metrics

edge list
```{r}
edge_list <- df_qc %>%
  select(Inventors, Title, No) %>%
  inner_join(., select(., Inventors, No), by="No") %>%
  filter(Inventors.x != Inventors.y) %>%
  unique %>%
  arrange(Title, No)

# replace blanks with _
edge_list$Inventors.x <- gsub(" ", "_", edge_list$Inventors.x)
edge_list$Inventors.y <- gsub(" ", "_", edge_list$Inventors.y)
```

edge matrix
```{r}
unique_nodes <- unique(edge_list$Inventors.x)
edges_length <- length(unique_nodes)

edge_matrix <- matrix(, nrow = edges_length, ncol = edges_length, dimnames = list(unique_nodes, unique_nodes))


for(i in 1:edges_length) {
  
  prim_inventor <- edge_list[[i,"Inventors.x"]]
  sec_inventor <- edge_list[[i,"Inventors.y"]]
  edge_matrix[prim_inventor,sec_inventor] <- 1 
}

edge_matrix[is.na(edge_matrix)] = 0
```



# 3. Network visualization
# 4. Network analysis



### apply rules

```{r}
inventors <- df_qc[1,]$Inventors

inventors_split <- strsplit(inventors, "\n")

inventors_split[[1]][1]
```



